Repository team-journey/journey-server, pull requests merged in 2021-07, with the labels that each got.

#26 Feature/home/#25
  src/api/home.ts
  src/constant.ts
  src/dto/Home/HomeResponseDTO.ts
  src/index.ts
  src/interfaces/IUser.ts
  src/interfaces/IUserCourse.ts
  src/interfaces/IUsrChallenge.ts
  src/loader/db.ts
  src/middleware/auth.ts
  src/models/User.ts
  src/service/homeService.ts
  src/service/userService.ts
Labels: khyunjiee

#28 Docs/#27
  apidoc.json
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  apidoc/css/style.css
  apidoc/fonts/glyphicons-halflings-regular.eot
  apidoc/fonts/glyphicons-halflings-regular.svg
  apidoc/fonts/glyphicons-halflings-regular.ttf
  apidoc/fonts/glyphicons-halflings-regular.woff
  apidoc/fonts/glyphicons-halflings-regular.woff2
  apidoc/img/android-chrome-192x192.png
  apidoc/img/android-chrome-512x512.png
  apidoc/img/apple-touch-icon.png
  apidoc/img/favicon-16x16.png
  apidoc/img/favicon-32x32.png
  apidoc/img/favicon.ico
  apidoc/index.html
  apidoc/locales/ca.js
  apidoc/locales/cs.js
  apidoc/locales/de.js
  apidoc/locales/es.js
  apidoc/locales/fr.js
  apidoc/locales/it.js
  apidoc/locales/locale.js
  apidoc/locales/nl.js
  apidoc/locales/pl.js
  apidoc/locales/pt_br.js
  apidoc/locales/ro.js
  apidoc/locales/ru.js
  apidoc/locales/tr.js
  apidoc/locales/vi.js
  apidoc/locales/zh.js
  apidoc/locales/zh_cn.js
  apidoc/main.js
  apidoc/utils/handlebars_helper.js
  apidoc/utils/send_sample_request.js
  apidoc/utils/send_sample_request_utils.js
  apidoc/vendor/bootstrap.min.css
  apidoc/vendor/bootstrap.min.js
  apidoc/vendor/diff_match_patch.min.js
  apidoc/vendor/handlebars.min.js
  apidoc/vendor/jquery.min.js
  apidoc/vendor/list.min.js
  apidoc/vendor/lodash.custom.min.js
  apidoc/vendor/path-to-regexp/LICENSE
  apidoc/vendor/path-to-regexp/index.js
  apidoc/vendor/polyfill.js
  apidoc/vendor/prism.css
  apidoc/vendor/prism.js
  apidoc/vendor/require.min.js
  apidoc/vendor/semver.min.js
  apidoc/vendor/webfontloader.js
  src/api/apiDummy.ts
  src/api/auth.ts
  src/api/home.ts
  src/api/user.ts
  src/index.ts
  tsconfig.json
Labels: khyunjiee

#30 Feature/course/#29
  apidoc/api_data.js
  apidoc/api_data.json
  apidoc/api_project.js
  apidoc/api_project.json
  src/api/course.ts
  src/api/home.ts
  src/dto/Course/CourseLibrary/CourseLibraryResponseDTO.ts
  src/index.ts
  src/loader/db.ts
  src/models/Course.ts
  src/service/courseService.ts
Labels: khyunjiee

#35 Bug/auth/#33
  src/api/auth.ts
  src/interfaces/IUser.ts
  src/interfaces/IUserCourse.ts
  src/models/User.ts
  src/service/authService.ts
Labels: khyunjiee

#36 Bug/auth/#34
  src/service/authService.ts
  src/service/userService.ts
Labels: khyunjiee

#38 feat: 토큰 중복 처리 로직 삭제
  src/service/userService.ts
Labels: khyunjiee

#40 Model/#39
  src/interfaces/IUsrChallenge.ts
  src/models/User.ts
Labels: khyunjiee

#42 Release
  apidoc.json
  dist/api/auth.js
  dist/api/auth.js.map
  dist/api/course.js
  dist/api/course.js.map
  dist/api/home.js
  dist/api/home.js.map
  dist/api/user.js
  dist/api/user.js.map
  dist/config/index.js
  dist/config/index.js.map
  dist/constant.js
  dist/constant.js.map
  dist/dto/Course/CourseLibrary/CourseLibraryResponseDTO.js
  dist/dto/Course/CourseLibrary/CourseLibraryResponseDTO.js.map
  dist/dto/Home/HomeResponseDTO.js
  dist/dto/Home/HomeResponseDTO.js.map
  dist/dto/SignIn/UserSignInRequestDTO.js
  dist/dto/SignIn/UserSignInRequestDTO.js.map
  dist/dto/SignIn/UserSignInResponseDTO.js
  dist/dto/SignIn/UserSignInResponseDTO.js.map
  dist/dto/SignUp/UserSignUpRequestDTO.js
  dist/dto/SignUp/UserSignUpRequestDTO.js.map
  dist/dto/SignUp/UserSignUpResponseDTO.js
  dist/dto/SignUp/UserSignUpResponseDTO.js.map
  dist/index.js
  dist/index.js.map
  dist/interfaces/IFail.js
  dist/interfaces/IFail.js.map
  dist/loader/db.js
  dist/loader/db.js.map
  dist/middleware/auth.js
  dist/middleware/auth.js.map
  dist/models/Course.js
  dist/models/Course.js.map
  dist/models/User.js
  dist/models/User.js.map
  dist/service/authService.js
  dist/service/authService.js.map
  dist/service/courseService.js
  dist/service/courseService.js.map
  dist/service/homeService.js
  dist/service/homeService.js.map
  dist/service/userService.js
  dist/service/userService.js.map
  package.json
  src/dto/SignUp/UserSignUpRequestDTO.ts
  src/dto/SignUp/UserSignUpResponseDTO.ts
  src/interfaces/IHashtag.ts
  src/interfaces/IImage.ts
  src/service/authService.ts
Labels: khyunjiee

#43 Feature/home/#41
  src/dto/Home/HomeResponseDTO.ts
  src/interfaces/IChallenge.ts
  src/interfaces/IUserCourse.ts
  src/interfaces/IUsrChallenge.ts
  src/loader/db.ts
  src/models/Course.ts
  src/models/User.ts
  src/service/authService.ts
  src/service/homeService.ts
  src/service/userService.ts
Labels: khyunjiee

#46 Feature/course/#45
  src/dto/Course/CourseLibrary/CourseLibraryResponseDTO.ts
  src/dto/Home/HomeResponseDTO.ts
  src/service/courseService.ts
  src/service/homeService.ts
Labels: khyunjiee

#48 Feature/course/#47
  src/api/course.ts
  src/dto/Course/CourseProgress/CourseProgressResponseDTO.ts
  src/service/courseService.ts
Labels: khyunjiee

#50 Feature/challenge/#49
  src/api/challenge.ts
  src/dto/Challenge/TodayChallenge/TodayChallengeResponseDTO.ts
  src/index.ts
  src/service/challengeService.ts
Labels: khyunjiee

#52 Feature/challenge/#51
  src/api/challenge.ts
  src/dto/Challenge/StampChallenge/StampChallengeResponseDTO.ts
  src/formatter/challengeDateFormatter.ts
  src/service/challengeService.ts
Labels: khyunjiee

#54 Feature/challenge/#53
  src/api/challenge.ts
  src/dto/Challenge/GetChallenge/GetChallengeResponseDTO.ts
  src/service/challengeService.ts
Labels: khyunjiee

#58 Feature/small satisfaction/#44
  src/api/auth.ts
  src/api/course.ts
  src/api/home.ts
  src/api/smallSatisfactionCommunity.ts
  src/api/user.ts
  src/api/writeSmallSatisfaction.ts
  src/controller/controllerDummy.ts
  src/controller/messageController.ts
  src/dto/SmallSatisfaction/Community/response/SmallSatisfactionCommunityResponseDTO.ts
  src/dto/SmallSatisfaction/Detail/response/SmallSatisfactionDetailResponseDTO.ts
  src/dto/SmallSatisfaction/Like/request/SmallSatisfactionLikeRequestDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/response/SmallSatisfactionMyDrawerResponseDTO.ts
  src/dto/SmallSatisfaction/Write/request/SmallSatisfactionWriteDTO.ts
  src/dto/dtoDummy.ts
  src/index.ts
  src/interfaces/ISmallSatisfaction.ts
  src/loader/message.ts
  src/middleware/middlewareDummy.ts
  src/models/SmallSatisfaction.ts
  src/service/serviceDummy.ts
  src/service/smallSatisfactionCommunityService.ts
  src/service/writeSmallSatisfactionService.ts
Labels: feat, kiyeon

#62 Docs/small satisfaction/#61
  src/api/smallSatisfactionCommunity.ts
  src/api/writeSmallSatisfaction.ts
Labels: docs

#63 Bug/challenge/#57
  src/api/challenge.ts
  src/controller/dateController.ts
  src/interfaces/IUser.ts
  src/interfaces/IUserSurccessChallenge.ts
  src/models/User.ts
  src/service/challengeService.ts
  src/service/courseService.ts
Labels: khyunjiee

#66 Feature/course/#55
  src/api/course.ts
  src/dto/Course/CourseMedal/CourseMedalResponseDTO.ts
  src/service/challengeService.ts
  src/service/courseService.ts
Labels: khyunjiee

#67 Docs/#56
  src/api/challenge.ts
  src/api/course.ts
  src/api/home.ts
  src/api/user.ts
Labels: khyunjiee

#69 Bug/challenge/#68
  src/service/challengeService.ts
  src/service/courseService.ts
Labels: khyunjiee

#71 Feature/small satisfaction/#70
  src/dto/SmallSatisfaction/Community/response/SmallSatisfactionCommunityResponseDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/response/SmallSatisfactionMyDrawerResponseDTO.ts
  src/service/smallSatisfactionCommunityService.ts
  src/service/smallSatisfactionMyDrawerService.ts
Labels: feat, kiyeon

#73 style: 소확행 내서랍장 조회 기능 수정
  src/service/smallSatisfactionMyDrawerService.ts
Labels: kiyeon, style

#76 feat: 연속 성공 date 비교 수정
  src/service/challengeService.ts
Labels: khyunjiee

#78 docs: apidoc header 수정
  src/api/challenge.ts
  src/api/course.ts
  src/api/home.ts
Labels: khyunjiee

#80 feat: jwt 토큰 만료시간 삭제
  src/service/authService.ts
  src/service/userService.ts
Labels: khyunjiee

#87 Feature/auth/#85
  src/api/password.ts
  src/index.ts
  src/interfaces/ISuccess.ts
  src/service/passwordService.ts
Labels: khyunjiee

#89 model: Course 모델 수정
  src/loader/db.ts
  src/models/Course.ts
Labels: khyunjiee

#91 Feature/small satisfaction/#86
  src/api/smallSatisfactionMyDrawer.ts
  src/service/smallSatisfactionMyDrawerService.ts
Labels: feat, kiyeon

#96 Feature/auth/#95
  package.json
  src/config/index.ts
  src/controller/password.ts
  src/dto/Password/CheckEmailResponseDTO.ts
  src/service/passwordService.ts
Labels: khyunjiee

#98 Feature/auth/#97
  src/api/password.ts
  src/dto/Password/ChangePasswordRequestDTO.ts
  src/dto/Password/ChangePasswordResponseDTO.ts
  src/service/passwordService.ts
Labels: khyunjiee

#101 Feature/home/#100
  src/api/course.ts
  src/api/home.ts
  src/dto/Home/HomeResponseDTO.ts
  src/service/authService.ts
  src/service/challengeService.ts
  src/service/courseService.ts
  src/service/homeService.ts
  src/service/passwordService.ts
  src/service/userService.ts
Labels: khyunjiee

#99 Feature/small satisfaction/#92
  src/api/smallSatisfaction.ts
  src/api/smallSatisfactionCommunity.ts
  src/api/smallSatisfactionMyDrawer.ts
  src/api/writeSmallSatisfaction.ts
  src/dto/SmallSatisfaction/Community/response/SmallSatisfactionCommunityResponseDTO.ts
  src/dto/SmallSatisfaction/Detail/response/SmallSatisfactionDetailResponseDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/request/SmallSatisfactionMyDrawerRequestDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/response/SmallSatisfactionMyDrawerResponseDTO.ts
  src/index.ts
  src/interfaces/ISmallSatisfaction.ts
  src/models/SmallSatisfaction.ts
  src/service/smallSatisfactionCommunityService.ts
  src/service/smallSatisfactionMyDrawerService.ts
  src/service/smallSatisfactionService.ts
  src/service/writeSmallSatisfactionService.ts
Labels: feat, kiyeon

#102 Feature/small satisfaction/#74
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Like/request/SmallSatisfactionLikeRequestDTO.ts
  src/dto/SmallSatisfaction/Like/response/LikeResponseDTO.ts
  src/models/SmallSatisfaction.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#104 Feature/small satisfaction/#103
  src/api/smallSatisfaction.ts
  src/service/smallSatisfactionService.ts
Labels: docs, feat, kiyeon

#108 Feature/small satisfaction/#106
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Delete/response/DeleteResponseDTO.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#109 Feature/small satisfaction/#107
  package.json
  src/api/smallSatisfaction.ts
  src/models/SmallSatisfaction.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#112 Refactoring/home/#110
  .gitignore
  src/api/home.ts
  src/service/homeService.ts
Labels: khyunjiee

#114 feat: hasLike 수정
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Community/response/SmallSatisfactionCommunityResponseDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/response/SmallSatisfactionMyDrawerResponseDTO.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#117 [Docs] apidoc 수정
  src/api/smallSatisfaction.ts
Labels: docs, kiyeon

#119 docs: apidoc 이미지 png를 Url로 변경
  src/api/smallSatisfaction.ts
Labels: docs, kiyeon

#123 Feature/small satisfaction/#120
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Create/response/CreateSmallSatisfactionDTO.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#127 Feature/small satisfaction/#126
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Community/response/SmallSatisfactionCommunityResponseDTO.ts
  src/dto/SmallSatisfaction/Detail/response/SmallSatisfactionDetailResponseDTO.ts
  src/dto/SmallSatisfaction/MyDrawer/response/SmallSatisfactionMyDrawerResponseDTO.ts
  src/dto/SmallSatisfaction/Write/request/SmallSatisfactionWriteDTO.ts
  src/interfaces/ISmallSatisfaction.ts
  src/models/SmallSatisfaction.ts
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#131 Model/course/#129
  src/api/challenge.ts
  src/api/course.ts
  src/api/home.ts
  src/dto/Challenge/GetChallenge/GetChallengeResponseDTO.ts
  src/dto/Challenge/StampChallenge/StampChallengeResponseDTO.ts
  src/dto/Challenge/TodayChallenge/TodayChallengeResponseDTO.ts
  src/dto/Course/CourseLibrary/CourseLibraryResponseDTO.ts
  src/dto/Course/CourseMedal/CourseMedalResponseDTO.ts
  src/dto/Course/CourseProgress/CourseProgressResponseDTO.ts
  src/dto/Home/HomeResponseDTO.ts
  src/interfaces/IChallenge.ts
  src/interfaces/ICourse.ts
  src/loader/db.ts
  src/models/Course.ts
  src/service/challengeService.ts
  src/service/courseService.ts
  src/service/homeService.ts
  src/service/userService.ts
Labels: docs, khyunjiee, model

#130 [소확행] 소확행 커뮤니티 작성 버튼 수정
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#135 feat: 소확행 커뮤니티 오류 수정
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#133 feat: 소확행 커뮤니티 서비스로직 오늘 게시물만 가져오도록 query문 추가
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#137 bug: 소확행 작성 해시태그 에러처리 제거
  src/api/smallSatisfaction.ts
Labels: bug, kiyeon

#139 feat: 푸시 알람 시 유저 토큰 get api 구현
  src/api/message.ts
  src/index.ts
Labels: khyunjiee

#145 feat: 소확행 작성 JSON으로 받기
  src/api/smallSatisfaction.ts
Labels: feat, kiyeon

#148 docs: 소확행 작성 apidoc 수정
  src/api/smallSatisfaction.ts
Labels: docs, kiyeon

#143 refactor: 소확행 작성시 날짜 response 삭제
  src/api/smallSatisfaction.ts
  src/dto/SmallSatisfaction/Create/response/CreateSmallSatisfactionDTO.ts
  src/service/smallSatisfactionService.ts
Labels: kiyeon, refactoring

#150 feat: 소확행 커뮤니티 작성하기 버튼 수정
  src/service/smallSatisfactionService.ts
Labels: feat, kiyeon

#151 style: console.log 삭제
  src/service/smallSatisfactionService.ts
Labels: kiyeon, style
